(define (make-mobile left right)
  (list left right))
(define (make-branch len structure)
  (list len structure))
(define (left-branch m)
  (car m))
(define (right-branch m)
  (car (cdr m)))
(define (branch-length b)
  (car b))
(define (branch-structure b)
  (car (cdr b)))
(define (total-weight m)

