(define (draw-test)
  (let ((device (make-graphics-device (car (enumerate-graphics-types))))
        (x-start 0)
        (y-start 0)
        (x-end 5)
        (y-end 5))
        (graphics-draw-line device x-start y-start x-end y-end)
        ; (graphics-close device)
        ))
